### PR TITLE
Update AbstractNode.cs

### PR DESCRIPTION
**Pull request by visualserg**
Sometimes default culture has ','

### CODE REVIEW

**Comment by schroef** [comment]
I tried building this with visual code 2019.
When i try to use it, it keeps returning this error.
Sorry for bothering here, there is no issue section. I know nothing about C++

```
Decoding C:/Users/romboutversluijs/Downloads/JSXbin
Decoding failed. If this problem persists, please raise an issue on github. Error message: Could not find file 'C:\Users\XXXXXXXXXXX\Downloads\JSXbin'.. Stacktrace:    at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.StreamReader..ctor(String path, Encoding encoding, Boolean detectEncodingFromByteOrderMarks, Int32 bufferSize, Boolean checkHost)
   at System.IO.File.InternalReadAllText(String path, Encoding encoding, Boolean checkHost)
   at System.IO.File.ReadAllText(String path, Encoding encoding)
   at jsxbin_to_jsx.Program.Decode(DecodeArgs decoderArgs) in C:\Users\XXXXXXX\Downloads\JSXbin Convertor\jsxbin-to-jsx-converter-1.6\jsxbin_to_jsx\Program.cs:line 45.
```

**Comment by schroef** [comment]
Okay found the issue, it doesnt like spaces nor dashes in its naming. Moved folder to root of download, changed spaces to underscore and returned an jsx file

**Comment by Edward-FX** [comment]
Hello, help please, I'm a newbie, how can I run this at all? what program can I use for a lesson, I don’t understand anything at all how to use it and how to **decode jsbin in jsx**

**Comment by linhndd** [comment]
> Hello, help please, I'm a newbie, how can I run this at all? what program can I use for a lesson, I don’t understand anything at all how to use it and how to **decode jsbin in jsx**

Hello. You can install visual studio and open it via VS. After that, you need debug or release it and get a file .exe in folder bin/debug or bin/release. Open your cmd and cd to your folder of .exe file and run command line above. This is steps by steps guidedance.

**Comment by linhndd** [comment]
> Hello, help please, I'm a newbie, how can I run this at all? what program can I use for a lesson, I don’t understand anything at all how to use it and how to **decode jsbin in jsx**

Hello, Contact me via skype linhndd.rtbed if you really want to run it. I will guidedance step by step to you.

**Comment by Edward-FX** [comment]
Thanks, maybe Discord? If you have this program

>

**Comment by muriloneo** [comment]
just tried and got a lot of errors like:

`Stacktrace:    em jsxbin_to_jsx.JsxbinDecoding.AbstractNode.DecodeNode() na C:\GIT\murilo\jsxbin-to-jsx-converter\jsxbin_to_jsx\JsxbinDecoding\AbstractNode.cs:linha 139
   em jsxbin_to_jsx.JsxbinDecoding.MemberExpr.Decode() na C:\GIT\murilo\jsxbin-to-jsx-converter\jsxbin_to_jsx\JsxbinDecoding\MemberExpr.cs:linha 27
   em jsxbin_to_jsx.JsxbinDecoding.AbstractNode.DecodeNode() na C:\GIT\murilo\jsxbin-to-jsx-converter\jsxbin_to_jsx\JsxbinDecoding\AbstractNode.cs:linha 134
   em jsxbin_to_jsx.JsxbinDecoding.MemberExpr.Decode() na C:\GIT\murilo\jsxbin-to-jsx-converter\jsxbin_to_jsx\JsxbinDecoding\MemberExpr.cs:linha 27
   em jsxbin_to_jsx.JsxbinDecoding.AbstractNode.DecodeNode() na C:\GIT\murilo\jsxbin-to-jsx-converter\jsxbin_to_jsx\JsxbinDecoding\AbstractNode.cs:linha 134
   em jsxbin_to_jsx.JsxbinDecoding.AssignmentExpr.Decode() na C:\GIT\murilo\jsxbin-to-jsx-converter\jsxbin_to_jsx\JsxbinDecoding\AssignmentExpr.cs:linha 31
   em jsxbin_to_jsx.JsxbinDecoding.AbstractNode.DecodeNode() na C:\GIT\murilo\jsxbin-to-jsx-converter\jsxbin_to_jsx\JsxbinDecoding\AbstractNode.cs:linha 134
   em jsxbin_to_jsx.JsxbinDecoding.ExprNode.Decode() na C:\GIT\murilo\jsxbin-to-jsx-converter\jsxbin_to_jsx\JsxbinDecoding\ExprNode.cs:linha 42
   em jsxbin_to_jsx.JsxbinDecoding.AbstractNode.DecodeNode() na C:\GIT\murilo\jsxbin-to-jsx-converter\jsxbin_to_jsx\JsxbinDecoding\AbstractNode.cs:linha 134
   em jsxbin_to_jsx.JsxbinDecoding.AbstractNode.DecodeChildren() na C:\GIT\murilo\jsxbin-to-jsx-converter\jsxbin_to_jsx\JsxbinDecoding\AbstractNode.cs:linha 449
   em jsxbin_to_jsx.JsxbinDecoding.StatementList.Decode() na C:\GIT\murilo\jsxbin-to-jsx-converter\jsxbin_to_jsx\JsxbinDecoding\StatementList.cs:linha 48
   em jsxbin_to_jsx.JsxbinDecoding.AbstractNode.DecodeNode() na C:\GIT\murilo\jsxbin-to-jsx-converter\jsxbin_to_jsx\JsxbinDecoding\AbstractNode.cs:linha 134
   em jsxbin_to_jsx.JsxbinDecoding.AbstractNode.DecodeLineInfo() na C:\GIT\murilo\jsxbin-to-jsx-converter\jsxbin_to_jsx\JsxbinDecoding\AbstractNode.cs:linha 415
   em jsxbin_to_jsx.JsxbinDecoding.FunctionDeclaration.Decode() na C:\GIT\murilo\jsxbin-to-jsx-converter\jsxbin_to_jsx\JsxbinDecoding\FunctionDeclaration.cs:linha 36
   em jsxbin_to_jsx.JsxbinDecoding.AbstractNode.DecodeNode() na C:\GIT\murilo\jsxbin-to-jsx-converter\jsxbin_to_jsx\JsxbinDecoding\AbstractNode.cs:linha 134
   em jsxbin_to_jsx.JsxbinDecoding.StatementList.Decode() na C:\GIT\murilo\jsxbin-to-jsx-converter\jsxbin_to_jsx\JsxbinDecoding\StatementList.cs:linha 45
   em jsxbin_to_jsx.JsxbinDecoding.AbstractNode.DecodeNode() na C:\GIT\murilo\jsxbin-to-jsx-converter\jsxbin_to_jsx\JsxbinDecoding\AbstractNode.cs:linha 134
   em jsxbin_to_jsx.JsxbinDecoding.AbstractNode.DecodeLineInfo() na C:\GIT\murilo\jsxbin-to-jsx-converter\jsxbin_to_jsx\JsxbinDecoding\AbstractNode.cs:linha 415
   em jsxbin_to_jsx.JsxbinDecoding.FunctionDeclaration.Decode() na C:\GIT\murilo\jsxbin-to-jsx-converter\jsxbin_to_jsx\JsxbinDecoding\FunctionDeclaration.cs:linha 36
   em jsxbin_to_jsx.JsxbinDecoding.AbstractNode.DecodeNode() na C:\GIT\murilo\jsxbin-to-jsx-converter\jsxbin_to_jsx\JsxbinDecoding\AbstractNode.cs:linha 134
   em jsxbin_to_jsx.JsxbinDecoding.RootNode.Decode() na C:\GIT\murilo\jsxbin-to-jsx-converter\jsxbin_to_jsx\JsxbinDecoding\RootNode.cs:linha 26
   em jsxbin_to_jsx.JsxbinDecoding.AbstractNode.Decode(String jsxbin, Boolean printStructure) na C:\GIT\murilo\jsxbin-to-jsx-converter\jsxbin_to_jsx\JsxbinDecoding\AbstractNode.cs:linha 59
   em jsxbin_to_jsx.Program.Decode(DecodeArgs decoderArgs) na C:\GIT\murilo\jsxbin-to-jsx-converter\jsxbin_to_jsx\Program.cs:linha 48.`

**Review by otavioreis — APPROVED** [review]
I was uploading my PR to fix the exactly same problem. Please commit this change to the code. 

Thanks.

**Comment by Lyskia37** [comment]
Hey, sorry I'm quite inexperienced regarding this kind of stuff, but I need help,

I've been struggling to understand for a few hours on how to use Visual Studio to run the command line "jsxbin_to_jsx encoded.jsxbin decoded.jsx"
1. Is it correct that i can write the command there and then press F5 ? (the properties > start option > command line arguments ?). If not how can I execute this command ?
2. Should i write something like "-v jsxbin_to_jsx myscript.jsxbin myscript.jsx" or "jsxbin_to_jsx myscript.jsxbin myscript.jsx", I tried both and it doesn't seem to work, it it something else ? 
3. Do I need to already have an empty myscript.jsx file somewhere ? I suppose i don't need because it will be generated but where is it supposed to be generated ?
4. Also where in my folders is supposed to be the "myscript.jsxbin" file I would like to decompile ?
5. Does someone know why those issues happen and how to fix it please ?

helpmeplz

**Comment by linhndd** [comment]
Hello @Lyskia37 , pls check your skype if you are available. For this case.

1. You need config .NET framework environment variable for run command: jsxbin_to_jsx
2. The command: jsxbin_to_jsx use in the folder debug and via command line prompt of window, you can not use it anywhere
3. Pls put the file encode.jsxbin into debug folder
4. You don't need make empty file jsx, script will be make it after run decode command line

**Comment by uwanoo** [comment]
hi how to fix ??
image
image
image

**Comment by schroef** [comment]
@uwanoo 
My guess is that the decoder is not updated to newer created version of jsxbin. I've seen sort of simular issues. Where some jsxbin file si.ply would not work

**Pull request closed without merging**
